baseURL = 'https://vipulvpatil.dev/'
languageCode = 'en-us'
title = 'Vipul V Patil'

[services]
  [services.googleAnalytics]
    ID = 'G-00WGRM6QLY'

[params]
  mediumRoot = 'https://vipulvpatil.medium.com'
  [params.controller]
    [params.controller.a]
      url = 'work'
      target = '_self'
      icon = 'icons/briefcase.svg'
    [params.controller.b]
      url = 'mailto:vipulvpatil@gmail.com'
      target = '_self'
      icon = 'icons/send.svg'
    [params.controller.up]
      url = 'http://twitter.com/vipulvpatil'
      target = '_blank'
      icon = 'icons/twitter.svg'
    [params.controller.right]
      url = 'http://github.com/vipulvpatil'
      target = '_blank'
      icon = 'icons/github.svg'
    [params.controller.down]
      url = 'http://instagram.com/vipulvpatil'
      target = '_blank'
      icon = 'icons/instagram.svg'
    [params.controller.left]
      url = 'http://linkedin.com/in/vipulvpatil'
      target = '_blank'
      icon = 'icons/linkedin.svg'

[menus]
  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 10
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 20
  [[menus.main]]
    name = 'Work'
    pageRef = '/work'
    weight = 30
  [[menus.main]]
    name = 'Interests'
    pageRef = '/interest'
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
