baseURL = 'https://vipulvpatil.github.io/me/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
  [[params.info]]
    url = '/work'
    target = '_self'
    icon = '/icons/briefcase.svg'
  [[params.info]]
    url='mailto:vipulvpatil@gmail.com'
    target = '_blank'
    icon = '/icons/send.svg'
  [[params.info]]
    url='http://twitter.com/vipulvpatil'
    target = '_blank'
    icon = '/icons/twitter.svg'
  [[params.info]]
    url='http://github.com/vipulvpatil'
    target = '_blank'
    icon = '/icons/github.svg'
  [[params.info]]
    url='http://instagram.com/vipulvpatil'
    target = '_blank'
    icon = '/icons/instagram.svg'
  [[params.info]]
    url='http://linkedin.com/in/vipulvpatil'
    target = '_blank'
    icon = '/icons/linkedin.svg'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 20
  [[menus.main]]
    name = 'About'
    pageRef = '/about'
    weight = 30
  [[menus.main]]
    name = 'Work'
    pageRef = '/work'
    weight = 40
  [[menus.main]]
    name = 'Interests'
    pageRef = '/interest'
    weight = 50

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
